# Generated by Django 5.1.4 on 2024-12-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='Instrument_type',
            new_name='instrument_type',
        ),
    ]
